# Generated by Django 4.2.1 on 2023-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190228_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ccon',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='con',
            field=models.CharField(default='', max_length=500),
        ),
    ]
