# Generated by Django 4.2.1 on 2023-06-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_chead0_blogpost_cintrohead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
    ]
