# Generated by Django 4.2.1 on 2023-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
