# Generated by Django 4.2.1 on 2023-06-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='introhead',
        ),
    ]
