# Generated by Django 4.2.1 on 2023-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpost_introhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
