# Generated by Django 4.2.1 on 2023-06-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_author_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Technology'), ('3', 'Cooking'), ('4', 'Education and Facts'), ('5', 'GK'), ('6', 'News'), ('7', 'Gaming'), ('8', 'Entertainment and Movies'), ('9', 'Sports'), ('10', 'Health and Fitness')], default='1', max_length=100),
        ),
    ]
