# Generated by Django 4.2.1 on 2023-06-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Technology'), ('3', 'Food'), ('4', 'Education and Facts'), ('5', 'GK'), ('6', 'News'), ('7', 'Gaming'), ('8', 'Entertainment and Movies'), ('9', 'Sports'), ('10', 'Lifestyle'), ('11', 'Travel'), ('12', 'Art and Design'), ('13', 'Music'), ('14', 'Finance'), ('15', 'Photography')], default='1', max_length=100),
        ),
    ]
